import tkinter

z = tkinter.Tk()

z.title("AZAWORK1")
z.geometry("400x400")
menu1 = tkinter.Menu(z)
z.config(menu=menu1)
filemenu = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="File", menu=filemenu)
filemenu.add_command(label= "New File")
filemenu.add_command(label="New Text File")
filemenu.add_separator()
filemenu.add_command(label = "Exit", command=z.destroy)
filemenu.add_command(label= "New window")
filemenu.add_command(label= "New window with profile")
filemenu.add_command(label= "Open file")
filemenu.add_command(label= "Open folder")
filemenu.add_command(label= "Open workspace from file")
filemenu.add_separator()
filemenu.add_command(label= "Open recent")
filemenu.add_separator()
filemenu.add_command(label= "Add foler to workspace")
filemenu.add_command(label= "Save workspace as")
filemenu.add_command(label= "Duplicate workspace")
filemenu.add_separator()
filemenu.add_command(label= "Save")
filemenu.add_command(label= "Save as")
filemenu.add_separator()
filemenu.add_command(label= "Share")
filemenu.add_command(label= "Auto save")
filemenu.add_command(label= "Preferences")
filemenu.add_separator()
filemenu.add_command(label= "Revert file")
filemenu.add_command(label= "Close editor")
filemenu.add_command(label= "Close folder")
filemenu.add_command(label= "Close win")

menu2 = tkinter.Menu(menu1,tearoff=0)
menu1.add_cascade(label="Edit", menu=menu2)
menu2.add_command(label = "Undo")
menu2.add_command(label="Redo")
menu2.add_separator()
menu2.add_command(label="Cut")
menu2.add_command(label="Copy")
menu2.add_command(label="Paste")
menu2.add_separator()
menu2.add_command(label="Find")
menu2.add_command(label="Replace")
menu2.add_separator()
menu2.add_command(label="Find in Files")
menu2.add_command(label="Replace in Files")
menu2.add_separator()
menu2.add_command(label="Toggle line Comment")
menu2.add_command(label="Toggle Block Comment")
menu2.add_command(label="Emmet: Expand Abbreviation")


menu3 = tkinter.Menu(menu1,tearoff=0)
menu1.add_cascade(label="Terminal", menu=menu3)
menu3.add_command(label="New Terminal")
menu3.add_command(label="Split Terminal")
menu3.add_separator()
menu3.add_command(label="Run task")
menu3.add_command(label="Run Build Task")
menu3.add_command(label="Run Active file")
menu3.add_command(label="Run selected text")
menu3.add_separator()
menu3.add_command(label="Show Running tasks")
menu3.add_command(label="Restar running tasks")
menu3.add_command(label ="Terminate tasks")
menu3.add_separator()
menu3.add_command(label="Comunicate Task")
menu3.add_command(label="Configure build task")





z.mainloop()